Add criteria builder, specifications and transactions
Everess/TwoModules pull request #2
Opened 2019-07-08 09:51 UTC by Everess

2019-07-08 12:32 UTC, PavelAndryushenko requested changes
Код посмотрел - в целом, неплохо, но есть важные моменты, которые нужно поправить, описал их в виде комментариев.
Я правильно понимаю, что ветка part-1 нам больше не нужна? Если да, то PR для нее нужно удалить, а саму ветку заморозить. Все исправления ошибок нужно делать в текущей ветке.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/build.gradle
> +    runtime group: 'org.flywaydb', name: 'flyway-gradle-plugin', version: '5.2.4'
Flyway должен запускаться при старте приложения без использования плагина, плагин по правилам проекта использовать нельзя.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/build.gradle
> +    compile group: 'org.springframework.boot', name: 'spring-boot-starter-web', version: '2.1.5.RELEASE'
compile - устаревшая опция, вместо нее нужно использовать implementation

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/controller/ShopController.java
> +    public ShopSpecs shopSpecs;
Зависимости нужно внедрять через конструктор, так мы сможем создавать экземпляр класса также и вне спрингового контекста

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/controller/ShopController.java
> +    public ShopSpecs shopSpecs;
Внедряемые объекты должны быть private - поскольку используются только в рамках класса, и final - поскольку должны инициализироваться только один раз.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/controller/ShopController.java
> +    public ShopRepo shopRepo;
Репозиторий не должен внедряться в контроллер - контроллер работает только с сервисным уровнем, а с репозиториями могут работать только сервисы.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/controller/ShopController.java
> +    public List<Shop> findShops() {
Это дореализовать нужно, как я понял?

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/controller/ShopController.java
> +        return shopRepo.findAll(
Со спецификациями, думаю, тоже нужно работать в сервисном слое, логика получения данных должна быть инкапсулирована и контроллер не должен ничего знать о том, как именно мы отбираем нужные данные.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/controller/ShopController.java
> +     * @return
В javadoc не должно быть пустых аннотаций - либо прописываем текст для них, либо удаляем.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/controller/ShopController.java
> +    public void createShops(@RequestBody ArrayList<Shop> shop) throws Exception {
Почему передаем список магазинов? У нас же ресурс - магазин, соответственно, создавать и редактировать мы должны именно магазин.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/dto/Shop.java
> +package secondModule.dto;
Почему сущность находится в пакете DTO? Для сущностей должен быть свой отдельный пакет.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/dto/Shop.java
> +    public int idShop;
В сущностях и dto нельзя использовать примитивы, поскольку они инициализируются значениями по умолчанию.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/dto/Shop.java
> +    public Long region;
Тут же явно ID региона, а не регион? Если поле - внешний ключ, то называть его нужно соответственно, а регион - это должна быть сущность, описывающая регион.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/repo/ShopRepo.java
> +public interface ShopRepo extends JpaRepository<Shop, Integer>, JpaSpecificationExecutor<Shop> {
Не очень удачное название для класса - ShopRepo - почему не назвать его ShopRepository?
Название пакета также должно быть repository - это прописано в правилах кодирования.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/repo/ShopRepo.java
> +    List<Shop> findShopByShopTitleAndRegion(String shopTitle, int region);
Region у тебя в сущности - Long, а здесь передается int.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/service/ShopService.java
> +    @Query(value = "SELECT * FROM shop", nativeQuery = true)
Зачем здесь Query, если в репозитории есть метод получения всех сущностей?

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/service/ShopService.java
> +    public void createShop(ArrayList<Shop> shop) throws Exception {
Всегда нужно оперировать с максимальным уровнем абстракции - если передается список, то передавать нужно List, а не ArrayList.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/service/ShopService.java
> +    public ShopSpecs shopSpecs;
Все свойства класса должны прописываться в начале класса до методов.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/service/ShopService.java
> +        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ru.easyjava.data.jpa.hibernate");
Все операции с запросами должны выполняться на уровне репозиториев.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/service/ShopService.java
> +        return shopRepo.getShopsByShopTitleAndRegion(shopTitle, region);
Ты правильно возвращаешь список магазинов посредством метода репозитория, но к чему, тогда, был весь остальной код этого метода?

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/java/secondModule/service/ShopService.java
> +    /**
Ненужный код нужно удалять - он не должен захламлять код, если какой-то задокументированный код нужно оставить, то нужно комментом описать, зачем он может быть нужен.

2019-07-08 12:32 UTC, PavelAndryushenko commented on SecondModule/src/main/resources/db/migration/V1__create_table_shop.sql
> +    idShop int8 not null,
Названия колонок в этом скрипте не совпадают с названиями колонок в сущностях и последующих скриптах - этот скрипт накатывался, он рабочий?

2019-07-09 07:35 UTC, Everess commented on SecondModule/src/main/java/secondModule/controller/ShopController.java
> +    public void createShops(@RequestBody ArrayList<Shop> shop) throws Exception {
На вход подавался список для проверки аннотации transactional и атрибута rollbackFor.

2019-07-11 07:51 UTC, closed without merging